import './async';
import './class';
import './destructuring';
import './for-of';
import './generator';
import './async-generator';
import './async-generator';
import './polyfills';
import './tagged';
